config/routes.rb
class SubdomainConstraint
  def self.matches?(request)
    subdomains = %w{ www }
    request.subdomain.present? && !subdomains.include?(request.subdomain)
  end
end

Rails.application.routes.draw do
  get 'home/index'

  constraints SubdomainConstraint do
    resources :courses
    resources :student_courses
    resources :students
  end

  resources :schools
  root :to => "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/school.rb
class School < ApplicationRecord
  searchkick text_middle: [:name]
  after_create :create_tenant

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, :presence => true
  validates :name, :presence => true
  validates :pitch, :presence => true
  validates :subdomain, :presence => true

  private

  def create_tenant
    Apartment::Tenant.create(subdomain)
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    if params[:keywords].present?
      @schools = School.search(params[:keywords], execute: false, fields: [:name], match: :text_middle)
      @courses = Course.search(params[:keywords], execute: false, fields: [:tittle], match: :text_middle)
      Searchkick.multi_search([@schools, @courses])
    end
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
    school = School.find(params[:id])
    Apartment::Tenant.switch!(school.subdomain)
    @total_students_active = StudentCourse.where(active: true).count
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_school
    @school = School.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def school_params
    params.require(:school).permit(:name, :email, :pitch, :subdomain)
  end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_with(model: school, local: true) do |form| %>
  <% if school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
        <% school.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :pitch %>
    <%= form.text_field :pitch %>
  </div>

  <div class="field">
    <%= form.label :subdomain %>
    <%= form.text_field :subdomain %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing School</h1>

<%= render 'form', school: @school %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<p id="notice"><%= notice %></p>
<p>This is a multi tenancy application</p>
<p>For use the resources student and course, please create the school first </p>
<p>If you'r trying to access the resources and already created a school go to <b>you_school</b>.lvh.me:3000 </p>

<div class="container">
  <form role="form" action="/schools">
    <h2 class="">Search School and courses</h2>
    <input type="text" class="form-control" placeholder="Ex: Marista" name="keywords">
    <br>
    <button class="btn btn-primary btn-block" type="submit">Search</button>
    <br>
  </form>

  <% if @schools.present? %>
    <h1>Schools: </h1>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Pitch</th>
          <th>Subdomain</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @schools.each do |school| %>
          <tr>
            <td><%= school.name %></td>
            <td><%= school.email %></td>
            <td><%= school.pitch %></td>
            <td><%= school.subdomain %></td>
            <td><%= link_to 'Show', school %></td>
            <td><%= link_to 'Edit', edit_school_path(school) %></td>
            <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  <br>

  <% if @courses.present? %>
    <h1>Courses: </h1>
    <table>
      <thead>
        <tr>
          <th>Tittle</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @courses.each do |course| %>
          <tr>
            <td><%= course.tittle %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  <% end %>
  <br>
</div>
<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>New School</h1>

<%= render 'form', school: @school %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @school.email %>
</p>

<p>
  <strong>Pitch:</strong>
  <%= @school.pitch %>
</p>

<p>
  <strong>Subdomain:</strong>
  <%= @school.subdomain %>
</p>

<p>
  <strong>Total students active:</strong>
  <%= @total_students_active %>
</p>

<td><%= link_to 'Students', students_path() %></td>
<br>
<td><%= link_to 'Courses', courses_path() %></td>
<br>
<td><%= link_to 'StudentCourses', student_courses_path() %></td>

<br>
<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>